# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Creates specialities
Speciality.create(sname: 'Accident and emergency medicine')
Speciality.create(sname: 'Allergology')
Speciality.create(sname: 'Anesthesiology')
Speciality.create(sname: 'Biological hematology')
Speciality.create(sname: 'Cardiology')
Speciality.create(sname: 'Child psychiatry')
Speciality.create(sname: 'Clinical biology')
Speciality.create(sname: 'Clinical chemistry')
Speciality.create(sname: 'Clinical neurophysiology')
Speciality.create(sname: 'Clinical radiology')
Speciality.create(sname: 'Dental, oral and maxillo-facial surgery')
Speciality.create(sname: 'Dermato-venerology')
Speciality.create(sname: 'Dermatology')
Speciality.create(sname: 'Endocrinology')
Speciality.create(sname: 'Gastro-enterologic surgery')
Speciality.create(sname: 'Gastroenterology')
Speciality.create(sname: 'General hematology')
Speciality.create(sname: 'General surgery')
Speciality.create(sname: 'Geriatrics')
Speciality.create(sname: 'Immunology')
Speciality.create(sname: 'Infectious diseases')
Speciality.create(sname: 'Internal medicine')
Speciality.create(sname: 'Laboratory medicine')
Speciality.create(sname: 'Maxillo-facial surgery')
Speciality.create(sname: 'Microbiology')
Speciality.create(sname: 'Nephrology')
Speciality.create(sname: 'Neuro-psychiatry')
Speciality.create(sname: 'Neurology')
Speciality.create(sname: 'Neurosurgery')
Speciality.create(sname: 'Nuclear medicine')
Speciality.create(sname: 'Obsetrics and gynecology')
Speciality.create(sname: 'Occupational medicine')
Speciality.create(sname: 'Ophthalmology')
Speciality.create(sname: 'Orthopaedics')
Speciality.create(sname: 'Otorhinolaryngology')
Speciality.create(sname: 'Pathology')
Speciality.create(sname: 'Pediatric surgery')
Speciality.create(sname: 'Pediatrics')
Speciality.create(sname: 'Pharmacology')
Speciality.create(sname: 'Physical medicine and rehabilitation')
Speciality.create(sname: 'Plastic surgery')
Speciality.create(sname: 'Psychiatry')
Speciality.create(sname: 'Public health')
Speciality.create(sname: 'Radiology')
Speciality.create(sname: 'Radiotherapy')
Speciality.create(sname: 'Respiratory medicine')
Speciality.create(sname: 'Rheumatology')
Speciality.create(sname: 'Stomatology')
Speciality.create(sname: 'Thoracic surgery')
Speciality.create(sname: 'Tropical medicine')
Speciality.create(sname: 'Urology')
Speciality.create(sname: 'Vascular surgery')
Speciality.create(sname: 'Venerology')